# -*- coding: utf-8 -*-
"""t01_qn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rTM3e83VfKsnhJcnozVnIR-f010KOoC

# COMP S493F Lab 1

In this lesson, you'll work on:

- Python collections and comprehension, and
- NumPy basics.

### Student name: *Please write your name here*
### Student ID: *Please write your 8-digit student ID here*

# Python collections

In Python, some commonly-used collections types are lists, tuples, sets, and dictionaries.

## Lists and tuples

A *list* is a sequence, or an ordered collection, of items. The `len()` function returns the number of items in a list.
"""

ls = [1, 2.0, "three"]
print(ls)
print(type(ls))
print(len(ls))

"""An individual item in a list can be accessed by integer indexing, with syntax `a_list[index]`. Note the f-string syntax: `f"{exp}"` displays the value of `exp`; `f"{exp=}"` displays the expression `exp`, an equal symbol, and the value of `exp` -- very useful for debugging and exploring code!"""

print(ls)
print(f"{ls[0]=}, {ls[1]=}")  # index is 0-based; index 0 -> first item
print(f"{ls[2]=}, {ls[-1]=}")  # index -1 -> last item

"""Multiple items in a list can be accessed by slicing, with syntax `a_list[start:stop:step]`. Note that the item at the `stop` index is excluded."""

print(ls)
print(f"{ls[2:6] = }")  # from index 2 (included) to index 6 (excluded)
print(f"{ls[:6] = }")  # start index 0 by default here
print(f"{ls[2:] = }")  # stop index len+1 (=7) by default here
print(f"{ls[:] = }")  # all items, i.e. making a copy
print(f"{ls[::2] = }")  # steps of 2, i.e. every other items
print(f"{ls[::-1] = }") # all items in reversed order

"""Lists are *mutable*, meaning that their contents may be changed during code execution."""

ls = [1, 2, 3]
print(ls)
ls[0] = 10  # modify the 1st item, i.e. with index 0
print(ls)
ls.append(40)  # append item at the end
print(ls)

"""A *tuple* is similar to a list, but *immutable*. That is, once created you cannot modify the contents of a tuple. A tuple has no `append()` method and so on."""

t = (1, 2.0, "three")
print(t)
print(type(t))
# t.append(40)  # no such method!

"""## Ranges

A *range* generates a sequence of consecutive, or equally-spaced, integers. It is often used with the `for` loop. The syntax is `range(start, stop, step)`, where `start` and `step` are optional. The meanings of the three parts are similar to those of list slicing syntax `a_list[start:stop:step]`. Again, note that the item of `stop` is excluded.
"""

for i in range(10):  # from 0 (included) to 10 (excluded)
    print(i, end=" ")  # print " " instead of "\n" at the end

for i in range(5, 10):  # from 5 (included) to 10 (excluded)
    print(i, end=" ")

for i in range(5, 10, 2):  # in steps of 2
    print(i, end=" ")

"""## Comprehension

*List comprehension* is a "Pythonic" way of generating a new list from an existing sequence of items. The basic syntax is shown below, where `if condition` is optional:

```python
[expr_using_item for item in sequence_of_items if condition]
```

Consider generating the squares of the numbers in an existing list. This can be done using a new list for storing the result and a `for` loop.
"""

ls = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # an existing sequence
squares = []  # for keeping result
for item in ls:
    squares.append(item * item)  # put to result
print(squares)

"""Using a list comprehension, the code is more concise and probably easier to read."""

ls = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # an existing sequence
squares = [item * item for item in ls]
print(squares)

"""A range can be used as the existing sequence of items."""

print([n * n for n in range(10)])

"""An optional `if` clause can be added to select items in the existing sequence based on a condition. For example, the squares of only odd numbers (i.e. `n % 2 == 1` is true when `n` is odd) are obtained as follows."""

print([n * n for n in range(10) if n % 2 == 1])

"""# Practice - Question 1 of 2

## Q1a

Lists can be nested; that is, a list can contain another list as an item. The following list `ls` contains three nested lists. Note that the lists may have different lengths. Multiple indexing operations may be used to access items in the nested lists. For example, `ls[0]` refers to the first (index 0) nested list, i.e. `[1, 2, 3, 4]`; `ls[0][2]` refers to the third (index 2) item in the nested list `ls[0]`, i.e. `3`.
"""

ls = [
    [1, 2, 3, 4],
    [5, 6],
    [7, 8, 9, 10]
]
print(ls[0][2])

"""Write code to print the value `8` in `ls` using two positive indices; i.e. write a statement like `print(ls[0][2])` but replace the indices `0` and `2` with other positive indices to display the value `8`.

Write code to print the value `8` in `ls` using two negative indices; i.e. write a statement like `print(ls[0][2])` but replace the indices `0` and `2` with two negative indices to display the value `8`.
"""

print(ls[2][1])
print(ls[-1][-3])

"""## Q1b

Write 4 lines of code to do the following:

- Create a list of integers from 0 to 11, with code `ls = list(range(12))`.
- Using `print()`, `ls`, and slicing, print the slice result `[6, 7, 8, 9, 10, 11]`.
- Using `print()`, `ls`, and slicing, print the slice result `[6, 8, 10]`.
- Using `print()`, `ls`, and slicing, print the slice result `[11, 8, 5, 2]`.
"""

ls = list(range(12))
print(ls[6:])
print(ls[6::2])
print(ls[::-3])

"""## Q1c

The following `is_prime(n)` function returns `True` if `n` is a prime number or `False` otherwise. Using this function and a list comprehension, write code to print the list of prime numbers between 2 and 1000, i.e. `[2, 3, 5, 7, ... 997]`. Hint: in a list comprehension, the expression using the item may be just the item, i.e. `[n for n in ...]`.
"""

def is_prime(n):
    for i in range(2, int(n ** 0.5 + 1)):
        if n % i == 0:
            return False
    return True

print([n for n in range(2, 1000) if is_prime(n)])

"""## &#x2766;

# NumPy basics

The NumPy library implements efficient multi-dimensional arrays and related operations. It is heavily used in machine learning libraries such as Scikit-learn and TensorFlow.

## Array creation and properties

By convention, NumPy is often imported as the name `np`. A NumPy array can be created using the `np.array()` function.
"""

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

"""The following code examines various properties of an array."""

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"{arr.size=}")  # number of items in array
print(f"{arr.shape=}")  # dimensions of array
print(f"{arr.ndim=}")  # number of dimensions, 1D or 2D etc
print(f"{arr.dtype=}")  # data type of items
print(f"{arr.itemsize=}")  # byte size of an item

"""In NumPy, a dimension is often called an *axis*; e.g. axis-0 means the first or most dominant dimension of an array.

We can change the dimensions, or shape, of an array using the `reshape()` method or function. Specifying `-1` as a dimension lets NumPy calculate that dimension according to the number of items in the array. `reshape()` would not modify the provided array but return a new array.
"""

arr2 = arr.reshape((3, -1))  # -1 becomes 6/3=2
print(arr2, arr2.shape)
print(arr, arr.shape)  # arr is not changed!

arr3 = np.reshape(arr, (6, 1))  # 2D array of 6x1 items
print(arr3, arr3.shape)

arr4 = np.reshape(arr, (6,))  # 1D array of 6 items
print(arr4, arr4.shape)

"""## More ways of creating arrays

There are many other ways of creating NumPy arrays. Some are shown below.
"""

a = np.zeros((2, 5)) # 2D array of 2x5 zeros
print(a)

a = np.ones(5) # 1D array of 5 ones, same as np.ones((5,))
a  # Colab automatically displays the last expression in a code cell

# No need to keep the array for later use; let's just display it
np.arange(0, 5, 0.5)  # 0 (included) to 5 (excluded) in steps of 0.5

"""## Array indexing

An item in an array can be accessed using indexing, with index values specified for the dimensions separated by commas, as `arr[r_index, c_index]` for a 2D array.
"""

a = np.arange(12).reshape((3, 4))
a

a[1, 2]  # index 1 -> second row, index 2 -> third column

"""A row is accessed using `arr[r_index]`, while a column using `arr[:, c_index]`. You may think of `:` to mean "all items" in a dimension or along an axis."""

a[1]  # index 1 -> second row, all columns; same as a[1, :]

a[:, 2]  # : -> all rows; index 2 -> third column

"""Multiple consecutive columns of an array can be accessed using a slice, i.e. `start:stop:step`, as the column index. The code below accesses the region of all rows and the second and third columns in the array."""

a[:, 1:3]  # : -> all rows, slice 1:3 -> second & third columns

"""# Practice - Question 2 of 2

## Q2a

Write code to do the following:

- Import NumPy as the name `np`.
- Create a 2D array of 4x5 items from 10 (included) to 30 (excluded). Use the `np.arange()` function and the `reshape()` method. Keep it in a variable called `arr`.
- Write `arr` in the last line of the code cell so that it is displayed in execution.
"""

import numpy as np
arr = np.arange(10, 30).reshape((4, 5))
arr

"""## Q2b

This part continues to use the `arr` variable above. Write code to display each of the following using `print()`, `arr` and array indexing:

- The value `15` in the array.
- The value `27` in the array.
- The last row, i.e. `[25, 26, 27, 28, 29]`.
- The second column, i.e. `[11, 16, 21, 26]`.
- The middle six numbers, i.e. `[[16, 17, 18], [21, 22, 23]]`.
"""

arr = np.arange(10, 30).reshape((4, 5))
print(arr[1, 0])
print(arr[3, 2])
print(arr[-1])
print(arr[:, 1])
print(arr[1:3, 1:4])

"""## Q2c

Write code to do the following with proper NumPy API:

- Seed the random number generator, with code `np.random.seed(42)`.
- Create an array of 10000 random numbers normally distributed with mean 0.0 and standard deviation 1.0. Use the `np.random.randn()` function, and keep the array in a variable called `xs`.
- Display the mean of the numbers in `xs`.
- Display the standard deviation of the numbers in `xs`.
- Display the number of elements (i.e. how many numbers) in `xs`.
"""

np.random.seed(42)
xs = np.random.randn(10000)
print(xs.mean())
print(xs.std())
print(xs.size)

"""## Q2d

This part continues to use the `xs` variable above. Write code to do the following:

- Import the matplotlib library, with code `import matplotlib.pyplot as plt`.
- Plot a histogram of the numbers in `xs` using 100 bins, with code `plt.hist(xs, bins=100);`. Note that the trailing semicolon `;` is specified so that the last expression value is not displayed.
"""

import matplotlib.pyplot as plt
from pathlib import Path
outputDirectory = Path(__file__).resolve().parent / "plots"
outputDirectory.mkdir(parents=True, exist_ok=True)
plt.hist(xs, bins=100);
plt.savefig(outputDirectory / "t01_q2d_histogram.png", dpi=150, bbox_inches="tight")
plt.show()
plt.close()

"""## &#x2766;

# Extras

## More list operations

Items can be removed from a list using the `del` operator or the `pop()` method.
"""

ls = [1, 2, 3, 4, 5]
print(ls)
del ls[1]  # remove the 2nd item, i.e. with index 1
print(ls)
ls.pop()  # remove item at the end
print(ls)

"""Some list functions modify list contents in-place (e.g. `extend()`); usually the return values of such functions are not used. Other functions and operations return copies or new lists (e.g. `+`), which are typically assigned to variables for later uses."""

ls = [1, 2, 3]
print(ls)
ls.extend([40, 50])  # add two items in-place
print(ls)  # ls is modified!

ls = [1, 2, 3]
print(ls)
ls2 = ls + [40, 50]  # add two items and put result to ls2
print(ls)  # ls is not modified!
print(ls2)  # result is in ls2

"""## Sets and dictionaries

A *set* is an unordered collection of unique items. If an item already exists in a set, adding another item of an equal value has no effect.
"""

s = {1, 2, "three", 1, 2.0, 1, 1}  # equal item skipped
print(s)
print(type(s))
print(len(s))

"""Use the `add()` method to add an item to a set, and the `in` operator to check if an item exists in a set."""

s = {1, 2, 3}
print(40 in s)
s.add(40)
print(40 in s)

"""A *dictionary* is a collection of key-value pairs with unique keys."""

d = {"one": 1, "two": 2, "three": 3, "two": 2.0}  # equal key overriding item
print(d)
print(type(d))
print(len(d))

"""Values in a dictionary can be accessed or added by indexing with the keys. Use the `in` operator to check if a key exists."""

print(d["one"])
print("four" in d)
d["four"] = 4  # add an item as the key doesn't exist
print("four" in d, d["four"])

"""### E1a

For each of the following expressions, write a statement to print the value of the expression, and the type of the value. For example, for an expression `set()`, the statement is `print(set(), type( set() ))`.

- `{}`
- `()`
- `(42)`
- `(42,)`

## NumPy operations along axes

Some NumPy operations can be applied to the whole array or along a certain axis of the array. E.g. in a 2D array, along axis-0 means across the rows downwards, while along axis-1 means across the columns towards the right.

The following code use `max()` to display the maximum value of an array, the maximum value of every column (along axis-0 or across rows downwards), and the maximum value of every row (along axis-1 or across columns towards the right). Note that the array contents are shuffled for more observable results.
"""

import numpy as np
arr = np.arange(12)
np.random.seed(42)  # reproducible random results
np.random.shuffle(arr)  # shuffle in-place, i.e. modify arr
arr = arr.reshape((3, 4))
print(arr)
print(f"{arr.max() = }")  # max of whole array; same as np.max(arr)
print(f"{arr.max(axis=0) = }")  # max of every column; np.max(arr, axis=0)
print(f"{arr.max(axis=1) = }")  # max of every row; np.max(arr, axis=1)

"""### E1b

Write code to create a 2D array of 3x3 integers from 0 (included) to 9 (excluded) in a random order (i.e. with contents shuffle). Display the array, the mean of the whole array, the mean of every column (along axis-0), the mean of every row (along axis-1); use the `np.mean(arr, axis=n)` function.

## Solutions to extra exercises

### E1a
"""

# Solution
print({}, type({}))
print((), type(()))
print((42), type((42)))
print((42,), type((42,)))

"""### E1b"""

# Solution
import numpy as np
arr = np.arange(9)
np.random.seed(42)  # reproducible random results
np.random.shuffle(arr)  # shuffle in-place, i.e. modify arr
arr = arr.reshape((3, 3))
print(arr)
print(f"{np.mean(arr) = }")  # mean of whole array; same as arr.mean()
print(f"{np.mean(arr, axis=0) = }")  # mean of every column; arr.mean(axis=0)
print(f"{np.mean(arr, axis=1) = }")  # mean of every row; arr.mean(axis=1)

"""## &#x2766;"""
