# -*- coding: utf-8 -*-
"""t02_qn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmOdqVrHEQhe1YJpMqeOa8G1aEGbMQ-T

# COMP 4930SEF Lab 2
"""

# Commented out IPython magic to ensure Python compatibility.
# %env TF_CPP_MIN_LOG_LEVEL=2

"""In this lesson, you'll work on:

- creating plots using Matplotlib, and
- running Keras code and plotting history.

### Student name: *Please write your name here*
### Student ID: *Please write your 8-digit student ID here*

# Creating plots using Matplotlib

*Matplotlib* is a Python library for creating charts, or plots. By convention, we import the `matplotlib.pyplot` module as the name `plt`.

## Line plots

The following is a very simple example of creating a line graph, or line plot. It uses the `plot()` function to plot a few `y` values stored in a list. The `x` values are by default the index values of the `y` list, i.e. `[0, 1, 2, 3]`. Since the `plot()` function call is the last expression in the code cell, Colab displays its return value.
"""

import matplotlib.pyplot as plt
from pathlib import Path
outputDirectory = Path(__file__).resolve().parent / "plots"
outputDirectory.mkdir(parents=True, exist_ok=True)
y = [1, 3, 2, 4]
plt.figure()
plt.plot(y)  # x data default to indices, i.e. [0, 1, 2, 3]
plt.savefig(outputDirectory / "t02_example_line_plot.png", dpi=150, bbox_inches="tight")
plt.close()

"""The next example plots the sine function. In order to obtain a smooth curve, we create 1000 `x` values from 0 to 2$\pi$ using the NumPy `np.linspace()` function. Then, the sine values of these `x` values are computed using the `np.sin(x)` function; this application of an operation (here sine) to all items in a NumPy array (here `x`) is called *vectorization*. After that, we set the x-axis label, y-axis label, and plot title. The semicolon `;` suppresses the last expression value in Colab."""

import numpy as np
x = np.linspace(0, 2 * np.pi, 1000)
y = np.sin(x)  # NumPy vectorization
plt.figure()
plt.plot(x, y)
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.title("The sine function")
plt.savefig(outputDirectory / "t02_example_sine_function.png", dpi=150, bbox_inches="tight")
plt.close()

"""Multiple curves can be drawn on the same plot. The code below invokes the `plot()` function two times to draw the sine and cosine curves. The `label` parameters in `plot()` specify the labels of the curves; to show these labels in a legend box, we call the `legend()` function."""

import numpy as np
x = np.linspace(0, 2 * np.pi, 1000)
plt.figure()
plt.plot(x, np.sin(x), label="sin(x)")
plt.plot(x, np.cos(x), label="cos(x)")
plt.legend()  # show the legend of labels
plt.xlabel("x")
plt.title("The sine and cosine functions")
plt.savefig(outputDirectory / "t02_example_sine_cosine_functions.png", dpi=150, bbox_inches="tight")
plt.close()

"""## Scatter plots

A scatter plot shows data points as dots (or other markers) without line segments joining the dots. In Matplotlib, two ways of creating scatter plots are specifying the `"o"` marker in the `plot()` function, and using the `scatter()` function. These are demonstrated below.

Here, 20 (instead of 1000) `x` values are used so that the dots can be seen clearly. In the `plot()` function call, the third argument `"or"` achieves two purposes: `"o"` for drawing big dots without joining line segments, and `"r"` for using the red color. The `scatter()` function draws the big dots using the default blue color.
"""

import numpy as np
x = np.linspace(0, 2 * np.pi, 20)  # 20 points for better view
plt.figure()
plt.plot(x, np.sin(x), "or", label="sin(x)")  # "o" --> big dots; "r" -> red
plt.scatter(x, np.cos(x), label="cos(x)")
plt.legend()  # show the legend of labels
plt.xlabel("x")
plt.title("The sine and cosine functions")
plt.savefig(outputDirectory / "t02_example_sine_cosine_scatter.png", dpi=150, bbox_inches="tight")
plt.close()

"""# Practice - Question 1 of 2

## Q1a

Write code to create a line graph of the tangent function as follows:

- Import the `matplotlib.pyplot` and `numpy` modules.
- Create an array of 1000 `x` values from 0 to 2$\pi$.
- Create an array called `y` to contain the tangent values of `x`. Use the `np.tan()` function.
- Plot the `x` and `y` values in a line graph.
- Set the x-axis label to "x", y-axis label to "tan(x)", the plot title to "The tangent function".
- Set the y limits of the plot to `[-10, 10]`, by calling `plt.ylim([-10, 10])`. This is done because Matplotlib tries to cater for huge tangent values, which makes the plot difficult to view; setting the y limits omits the effects of the huge tangent values.
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 2 * np.pi, 1000)
y = np.tan(x)
plt.figure()
plt.plot(x, y)
plt.xlabel("x")
plt.ylabel("tan(x)")
plt.title("The tangent function")
plt.ylim([-10, 10])
plt.savefig(outputDirectory / "t02_q1a_tangent_function.png", dpi=150, bbox_inches="tight")
plt.close()

"""## Q1b

Write code to create a line graph of the hyperbolic tangent, or tanh, function as follows.

- Use 1000 `x` values from -5 to 5.
- Compute the `y` values using the `np.tanh()` function.
- Plot the `x` and `y` values in a line graph.
- Set the x-axis and y-axis labels and the plot title properly.
"""

x = np.linspace(-5, 5, 1000)
y = np.tanh(x)
plt.figure()
plt.plot(x, y)
plt.xlabel("x")
plt.ylabel("tanh(x)")
plt.title("The hyperbolic tangent function")
plt.savefig(outputDirectory / "t02_q1b_hyperbolic_tangent.png", dpi=150, bbox_inches="tight")
plt.close()

"""## Q1c

Repeat the tanh plot in part b but using a scatter plot instead of a line graph. Specifically, copy the above program and make these changes:

- Use 50 `x` values (instead of 1000).
- Create a scatter plot (instead of a line graph). You may use either `plot()` or `scatter()`.
"""

x = np.linspace(-5, 5, 50)
y = np.tanh(x)
plt.figure()
plt.plot(x, y, "o")
plt.xlabel("x")
plt.ylabel("tanh(x)")
plt.title("The hyperbolic tangent function (scatter plot)")
plt.savefig(outputDirectory / "t02_q1c_hyperbolic_tangent_scatter.png", dpi=150, bbox_inches="tight")
plt.close()

"""## &#x2766;

# Running Keras code and plotting history

In this section, some Keras programs are provided to you for execution and plotting of history. Note that it is not required that you fully understand the Keras code, which is not the goal of this lesson.

## Perceptron and OR gate

The program below simulates a perceptron (which has output of either exactly 0 or 1) by a Keras sigmoid neuron (which has output of a floating point number between 0.0 and 1.0). The program trains the neuron, i.e. the model, to predict the OR gate outputs, and then displays the actual outputs and predicted outputs for the 4 training examples.
"""

# Simulate a perceptron by a sigmoid neuron,
# with a float output between 0.0 and 1.0.
import numpy as np
from tensorflow import keras
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = X[:, 0] | X[:, 1]
keras.utils.set_random_seed(42)
model = keras.models.Sequential([
    keras.layers.Dense(1, activation="sigmoid")
])
opt = keras.optimizers.RMSprop(learning_rate=.1)
model.compile(loss="binary_crossentropy", optimizer=opt, metrics=["acc"])
history = model.fit(X, y, epochs=300, verbose=0)
y_pred = model.predict(X, verbose=0)
print("Actual y:", y)
print("Predicted y:", y_pred.round(2).ravel())

"""As the actual outputs equal the predicted outputs, the model seems to be able to predict the OR gate outputs. Let's plot the performance of the model when it is trained. The training `history` is returned by `model.fit()`; note that `history.history` is a dictionary with two keys: "loss" and "acc"."""

print(type(history.history))
print(history.history.keys())

"""All in all, `history.history["loss"]` is a list of loss, or error, values for different epochs. `history.history["acc"]` is a list of accuracy values for different epochs.

This is a plot of the training loss, which decreases steadily to about 0 in 200 epochs.
"""

import matplotlib.pyplot as plt
plt.figure()
plt.plot(history.history["loss"])
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.savefig(outputDirectory / "t02_or_training_loss.png", dpi=150, bbox_inches="tight")
plt.close()

"""This is a plot of the training accuracy, which becomes 1.0 in a smaller number (<50) of epochs."""

plt.figure()
plt.plot(history.history["acc"])
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.savefig(outputDirectory / "t02_or_training_accuracy.png", dpi=150, bbox_inches="tight")
plt.close()

"""## Perceptron and XOR gate

The following program simulates a perceptron by a sigmoid neuron for predicting the XOR gate outputs.
"""

# Simulate a perceptron by a sigmoid neuron,
# with a float output between 0.0 and 1.0.
import numpy as np
from tensorflow import keras
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = X[:, 0] ^ X[:, 1]
keras.utils.set_random_seed(42)
model = keras.models.Sequential([
    keras.layers.Dense(1, activation="sigmoid")
])
opt = keras.optimizers.RMSprop(learning_rate=.1)
model.compile(loss="binary_crossentropy", optimizer=opt, metrics=["acc"])
history = model.fit(X, y, epochs=300, verbose=0)
y_pred = model.predict(X, verbose=0)
print("Actual y:", y)
print("Predicted y:", y_pred.round(2).ravel())

"""The differences between the actual outputs and predicted outputs indicate that a perceptron cannot predict the XOR gate outputs.

In the plot of the training loss below, the loss decreases initially but note that all the loss values are about 0.7! This is not good!

**Note that the code cell below must be executed after executing the preceding code cell, so that the `history` variable refers to the correct data. `history` refers to different objects throughout this notebook!**
"""

plt.figure()
plt.plot(history.history["loss"])
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.savefig(outputDirectory / "t02_xor_perceptron_training_loss.png", dpi=150, bbox_inches="tight")
plt.close()

"""In the plot of the training accuracy below, the accuracy values are mostly 0.5 -- not a good result."""

plt.figure()
plt.plot(history.history["acc"])
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.savefig(outputDirectory / "t02_xor_perceptron_training_accuracy.png", dpi=150, bbox_inches="tight")
plt.close()

"""# Practice - Question 2 of 2

## Q2a (Perceptron and AND gate)

The following program simulates a perceptron by a sigmoid neuron for predicting the AND gate outputs.
"""

# Simulate a perceptron by a sigmoid neuron,
# with a float output between 0.0 and 1.0.
import numpy as np
from tensorflow import keras
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = X[:, 0] & X[:, 1]
keras.utils.set_random_seed(42)
model = keras.models.Sequential([
    keras.layers.Dense(1, activation="sigmoid")
])
opt = keras.optimizers.RMSprop(learning_rate=.1)
model.compile(loss="binary_crossentropy", optimizer=opt, metrics=["acc"])
history = model.fit(X, y, epochs=300, verbose=0)
y_pred = model.predict(X, verbose=0)
print("Actual y:", y)
print("Predicted y:", y_pred.round(2).ravel())

"""Write code to create a plot of the training loss and a plot of the training accuracy. Make sure that you execute the above code cell and then your code cells of plotting."""

plt.figure()
plt.plot(history.history["loss"])
plt.xlabel("Epochs")
plt.ylabel("Loss");
plt.savefig(outputDirectory / "t02_and_training_loss.png", dpi=150, bbox_inches="tight")
plt.close()

plt.figure()
plt.plot(history.history["acc"])
plt.xlabel("Epochs")
plt.ylabel("Accuracy");
plt.savefig(outputDirectory / "t02_and_training_accuracy.png", dpi=150, bbox_inches="tight")
plt.close()

"""## Q2b (MLP and XOR gate)

The following program simulates a MLP of perceptrons by a MLP of sigmoid neurons for predicting the XOR gate outputs.
"""

# Simulate perceptrons in a MLP by sigmoid neurons,
# with a float output between 0.0 and 1.0.
import numpy as np
from tensorflow import keras
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = X[:, 0] ^ X[:, 1]
keras.utils.set_random_seed(42)
model = keras.models.Sequential([  # MLP
    keras.layers.Dense(2, activation="sigmoid"),
    keras.layers.Dense(1, activation="sigmoid")
])
opt = keras.optimizers.RMSprop(learning_rate=.1)
model.compile(loss="binary_crossentropy", optimizer=opt, metrics=["acc"])
history = model.fit(X, y, epochs=300, verbose=0)
y_pred = model.predict(X, verbose=0)
print("Actual y:", y)
print("Predicted y:", y_pred.round(2).ravel())

"""Write code to create a plot of the training loss and a plot of the training accuracy. Make sure that you execute the above code cell and then your code cells of plotting."""

plt.figure()
plt.plot(history.history["loss"])
plt.xlabel("Epochs")
plt.ylabel("Loss");
plt.savefig(outputDirectory / "t02_xor_mlp_training_loss.png", dpi=150, bbox_inches="tight")
plt.close()

plt.figure()
plt.plot(history.history["acc"])
plt.xlabel("Epochs")
plt.ylabel("Accuracy");
plt.savefig(outputDirectory / "t02_xor_mlp_training_accuracy.png", dpi=150, bbox_inches="tight")
plt.close()

"""## Q2c

In part b above, the data and model are simple, and more training epochs achieve better performance. Referring to the plot of training loss in part b, answer the following questions.

1. Is the training loss close to zero in 50 epochs?
1. Is the training loss close to zero in 200 epochs?
1. What is the smallest number of epochs that achieves a training loss close to zero?

Solution:


<div class='alert alert-warning' role='alert'><b>
<b>1. No </b>
<b>2. Yes </b>
<b>3. Approximately 150 epochs </b>
</b></div>

## &#x2766;

# Extras

## Creating multiple subplots in a figure

Matplotlib supports putting multiple subplots in a figure, with a layout of a table or grid. Subplots can be created using the `subplot(nrows, ncols, index)` function, where the 3 parameters specify the number of rows of subplots, the number of columns of subplots, and the index of the current subplot to work on.

In the example below, `subplot(1, 2, 1)` specifies to use 2 subplots in 1 row and 2 columns and to work on the first subplot subsequently; after that, we plot a sine curve in the first subplot using the `plot()` function and so on. Similarly, `subplot(1, 2, 2)` specifies to use 2 subplots again but then to work on the second subplot subsequently; after that, we plot the cosine curve in the second subplot.

The call to `figure(figsize=[8, 4])` near the beginning sets a figure size of 8 inches by 4 inches; this fits the two subplots to a better aspect ratio. The call to `tight_layout()` near the end sets a tight layout to avoid overlapping of the subplots.
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 2 * np.pi, 1000)
plt.figure(figsize=[8, 4])
plt.subplot(1, 2, 1)  # 1 row, 2 columns, do 1st plot; same as subplot(121)
plt.plot(x, np.sin(x))
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.title("The sine function")
plt.subplot(1, 2, 2)  # 1 row, 2 columns, do 2nd plot; same as subplot(122)
plt.plot(x, np.cos(x))
plt.xlabel("x")
plt.ylabel("cos(x)")
plt.title("The cosine function")
plt.tight_layout()  # fit layout and spacing
plt.savefig(outputDirectory / "t02_extra_two_subplots.png", dpi=150, bbox_inches="tight")
plt.close()

"""### E1a

Create a figure of 3 subplots: the sine, cosine, and tangent functions. Refer to the above example of 2 subplots and remember to set the y limits of the tangent subplot to `[-10, 10]`.

## Solutions to extra exercises

### E1a
"""

# Solution
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 2 * np.pi, 1000)
plt.figure(figsize=[9, 3])
plt.subplot(1, 3, 1)  # same as subplot(131)
plt.plot(x, np.sin(x))
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.title("The sine function")
plt.subplot(1, 3, 2)  # same as subplot(132)
plt.plot(x, np.cos(x))
plt.xlabel("x")
plt.ylabel("cos(x)")
plt.title("The cosine function")
plt.subplot(1, 3, 3)  # same as subplot(133)
plt.plot(x, np.tan(x))
plt.xlabel("x")
plt.ylabel("tan(x)")
plt.title("The tangent function")
plt.ylim([-10, 10])
plt.tight_layout()
plt.savefig(outputDirectory / "t02_extra_three_subplots.png", dpi=150, bbox_inches="tight")
plt.close()

"""## &#x2766;"""
